### ISSUE TITLE
Camera_Model.py Has an issue with python 3

### ISSUE THREAD

**Issue by geoeo** [oxford-ori/robotcar-dataset-sdk#1]
Hello,

It seems that the line 147 in Camera_Model.py no longer works with python 3.
`lut = lut.reshape([2, lut.size / 2])`

It can easily be fixed by using 
`lut = lut.reshape([2, lut.size // 2])`

This happens because Python 3 does not auto convert floats to integers in division

Best,

Marc

**Comment by podgib** [comment]
Thanks, I'll fix this. We've only tested with python 2, so not surprised there's issues with 3 - let us know if you find any others :)
